" Disable some default shortcuts for use with other plugins.
aunmenu Syntax
aunmenu Window
aunmenu Help

macmenu File.Print key=<nop>
macmenu File.New\ Tab key=<nop>
macmenu File.Open\.\.\. key=<nop>
macmenu File.Open\ Tab\.\.\. key=<nop>
macmenu File.Close key=<nop>

" Ctrl-P
nmap <D-t> :CtrlP<CR>
nmap <D-e> :CtrlPBuffer<CR>
nmap <D-r> :CtrlPFunky<CR>
imap <D-t> <Esc><D-t>
imap <D-e> <Esc><D-e>
imap <D-r> <Esc><D-r>

" set guifont=Menlo:h12 linespace=3
set guifont=Input\ Mono\ Narrow:h12 linespace=3

" Comments in italics.
augroup on_change_colorschema
  autocmd!
  autocmd ColorScheme * call Base16hi("Comment", "", "", "", "", "italic", "")
augroup END

colo base16-onedark

" hi StatusLine gui=bold guifg=#ffffff guibg=#000000
" hi StatusLineNC gui=bold guifg=#999999 guibg=#d0d0d0
