" vim:set ts=2 sts=2 sw=2 expandtab:

set nocompatible

filetype off


" -------
" Plugins
" -------

" Install vim-plug if needed.
if !filereadable(expand('~/.vim/autoload/plug.vim'))
  exec 'silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs '.
        \ 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
endif

call plug#begin('~/.vim/plugged')
  Plug 'pbrisbin/vim-mkdir'           " Automatically create non-existent directories when saving.
  Plug 'tpope/vim-repeat'             " 'repeat.vim: enable repeating supported plugin maps with .'.
  "Plug 'thinca/vim-quickrun'          " '*quickrun* is Vim plugin to execute whole/part of editing file'. Provides :QuickRun.
  Plug 'airblade/vim-rooter'          " 'Changes Vim working directory to project root (identified by presence of known directory or file)'.
  "Plug 'moll/vim-bbye'                " 'Delete buffers and close files in Vim without closing your windows.' Use with :Bdelete and :Bwipeout.
  Plug 'ludovicchabant/vim-gutentags' " 'A Vim plugin that manages your tag files.'
  Plug 'tpope/vim-eunuch'             " 'Vim sugar for the UNIX shell commands that need it the most'. Provides :Delete, :Move, :Rename, :SudoWrite, etc.
  Plug 'ctrlpvim/ctrlp.vim'           " 'Fuzzy file, buffer, mru, tag, etc finder'.
  Plug 'FelikZ/ctrlp-py-matcher'      " Better matching for ctrlp.
  Plug 'tpope/vim-sleuth'             " Heuristically set buffer options (shiftwidth, expandtab, etc.).
  Plug 'Raimondi/delimitMate'         " 'Provides insert mode auto-completion for quotes, parens, brackets, etc'
  Plug 'tpope/vim-surround'           " 'surround.vim: quoting/parenthesizing made simple'. Provides ds, cs, yss and visual S.
  Plug 'tomtom/tcomment_vim'          " 'tcomment provides easy to use, file-type sensible comments for Vim.' Provides gcc, gc{motion}.
  Plug 'vim-scripts/matchit.zip'      " Extended % matching for HTML, LaTeX, and many other languages.
  Plug 'machakann/vim-swap'           " Reorder/swap delimited items. Adds g<, g>, gs.
  Plug 'shawncplus/phpcomplete.vim'   " Improved PHP omnicompletion.
  Plug 'groenewege/vim-less'          " Syntax support for LESS.
  Plug 'mtdl9/vim-log-highlighting'   " Provides syntax highlighting for generic log files.
  Plug 'ap/vim-css-color'             " Preview CSS colors in source code while editing.
  Plug 'ap/vim-buftabline'            " 'Forget Vim tabs – now you can have buffer tabs'.
  Plug 'tpope/vim-fugitive'           " 'fugitive.vim: A Git wrapper so awesome, it should be illegal'.

  Plug 'chriskempson/base16-vim'
  Plug 'dracula/vim', { 'as': 'dracula' }

"   Plug 'tacahiroy/ctrlp-funky'        " 'A super simple function navigator for ctrlp.vim'.
"   Plug 'dyng/ctrlsf.vim'              " 'An ack.vim alternative mimics Ctrl-Shift-F on Sublime Text 2'.
"   Plug 'xolox/vim-session'            " Extended session management. Adds :{Open,Close,Delete}Session cmds.
"   Plug 'xolox/vim-misc'               " Required by xolox/vim-session.
"   Plug 'mileszs/ack.vim'              " 'Run your favorite search tool from Vim, with an enhanced results list'. Provides :Ack, :AckAdd, :LAck and :LAckAdd.
"   Plug 'skwp/greplace.vim'            " 'Global search and replace for VI'. Provides :Gsearch and :Greplace.
"   Plug 'maralla/completor.vim'        " 'Completor is an asynchronous code completion framework for vim8'.
"   Plug 'majutsushi/tagbar'            " Vim plugin that displays tags in a window, ordered by scope. Use with :TagbarToggle.
"   Plug 'mbbill/undotree'              " Undo tree visualizer (:UndotreeToggle).
"   Plug 'airblade/vim-gitgutter'
call plug#end()


" ------
" Basics
" ------

let mapleader = ","

filetype plugin indent on

syntax on

set autoread hidden nobackup nowritebackup noswapfile modeline
set fileformats=unix,dos,mac encoding=utf-8 fileencoding=utf-8
set clipboard=unnamed
set report=0
set shortmess=aAIc
set incsearch
set number relativenumber
set viminfo='100,<100,s10,h

set noerrorbells vb t_vb=             " Use visual bells instead of sound.
set whichwrap+=<,>,[,]                " Cursor keys move to prev/next lines too.
set gdefault                          " Default to replacing all ocurrences when searching & replacing.
set incsearch ignorecase smartcase    " Incremental search. Ignore case when searching, except if not all pattern is lowercase.
set showmatch                         " Show matching brackets.

set cursorline              " Highlight current line.
" set colorcolumn=+1
set noshowmode showcmd      " Last line: don't show current mode + show incomplete commands.
set scrolloff=5             " Always show some lines of context around the cursor.
set laststatus=2            " Always show status line.
set statusline=\ [%{mode()}]\ %.80f\ %h%m%r%w%=\|\%{strlen(&ft)?&ft:'?'}\ \|\%{strlen(&fenc)?&fenc:&enc}\ (%{&fileformat})\|\ %-8(%l:%c%)

set list listchars=tab:\›\ ,trail:· " Display tabs and trailing spaces.

set foldmethod=indent foldlevel=99 foldnestmax=4

" Enable persistent undo.
if has("persistent_undo")
    set undofile undodir=~/.vim-undodir/
endif

set nostartofline
set nowrap textwidth=120

set autoindent copyindent
set tabstop=4 softtabstop=4 shiftwidth=4
set expandtab smarttab

set formatoptions+=n " Recognize numbered lists.
set formatoptions-=t " Do not break lines at textwidth col.

set backspace=indent,eol,start " Backspace over everything.

set completeopt=menu,menuone,noinsert " Insert mode autocomplete.

set wildmenu wildmode=longest:full " Use wild menu for tab-completion.
set wildmode=longest:full
set wildignore+=.DS_Store,*/node_modules/*,*/vendors/*,*/.site/*,*.min.css,*.min.js,*.mo

" Use treeview for NetRW by default.
let g:netrw_liststyle=3

" Use rg.
set grepprg=/opt/homebrew/bin/rg\ --vimgrep\ --no-heading\ --smart-case


" --------
" Commands
" --------

augroup editing
  " When editing a file, always jump to the last cursor position.
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
augroup end

augroup makeprg
  au FileType php setl makeprg=php\ %
  au FileType python setl makeprg=python\ %
  au FileType ruby setl makeprg=ruby\ %
augroup end

augroup syntax
  "au FileType python setl omnifunc=pythoncomplete#Complete
  au FileType php setl omnifunc=phpcomplete#CompletePHP makeprg=php\ %
  au FileType ruby setl makeprg=ruby\ %
augroup end

augroup vimconf
  au!
  au BufWritePost vimrc so %
augroup end

" Command to remove trailing spaces.
command! RemoveTrailingWhitespace :%s/\s\+$//e


" -------------
" Plugin config
" -------------

let g:tcomment#filetype#guess_php=1

let delimitMate_expand_space=1

" buftabline.
let g:buftabline_show = 1
let g:buftabline_separators = 1
let g:buftabline_plug_max = 5

" vim-rooter.
let g:rooter_patterns = ['.project', '.vscode']
let g:rooter_silent_chdir = 1

" Store tags files outside of project directories.
let g:gutentags_cache_dir = '~/.cache/vim/vim-gutentags'

" CtrlP.
let g:ctrlp_use_caching = 0
let g:ctrlp_user_command = '/opt/homebrew/bin/rg %s --files --color=never --glob "" --no-ignore-vcs --iglob !.git/ --iglob !node_modules/ --iglob !.DS_Store --iglob !vendor/ --iglob !tmp/'
let g:ctrlp_match_window = 'top,order:ttb,min:1,max:20'
let g:ctrlp_show_hidden = 0
let g:ctrlp_match_func = { 'match': 'pymatcher#PyMatch' }
let g:ctrlp_max_files = 0
let g:ctrlp_open_multiple_files = 'ij'
let g:ctrlp_working_path_mode = ''
" let g:ctrlp_extensions = ['funky']


let g:phpcomplete_mappings = {
  \ 'jump_to_def': '<C-]>',
  \ 'jump_to_def_split': '',
  \ 'jump_to_def_vsplit': '',
  \ 'jump_to_def_tabnew': '',
  \}


" --------
" Mappings
" --------
noremap Q <nop>

" More clever navigation.
nnoremap 0 g0
nnoremap $ g$
nnoremap j gj
nnoremap k gk

" Visual shifting.
vnoremap < <gv
vnoremap > >gv

imap jj <Esc>

" Navigate through buffers using <Leader><,> and <Leader><.>
map <Leader>, :bn<CR>
map <Leader>. :bn<CR>

" Some path-related cmd mode expansions: %f[r] - file abs [or rel] path, %d[r] - dir abs [or rel] path.
cmap %f <C-R>=expand("%:p") <CR>
cmap %d <C-R>=expand("%:p:h") <CR>
cmap %rf <C-R>=expand("%:.") <CR>
cmap %rd <C-R>=expand("%:.:h") <CR>

" Similar to above, but copies file/dir paths to clipboard.
nnoremap <Leader>cf :let @*=expand("%:p")<CR>
nnoremap <Leader>cd :let @*=expand("%:p:h")<CR>
nnoremap <Leader>crf :let @*=expand("%:.")<CR>
nnoremap <Leader>crd :let @*=expand("%:.:h")<CR>

" Make Tab and Enter select inside the ins-menu.
inoremap <expr> <Tab> pumvisible() ? "\<C-y>" : "\<Tab>"
inoremap <expr> <CR>  pumvisible() ? "\<C-y>" : "\<CR>"

" Ctrl-P.
nmap <Leader>t :CtrlP<CR>
nmap <Leader>r :CtrlPBufTag<CR>


" -----------
" GVim/MacVim
" -----------
if has("gui_running")
	set guioptions=ceig
	set lines=40 columns=140

	" Use Cmt+T and Cmd+R for Ctrl-P
	nmap <D-t> <Leader>t
	nmap <D-r> <Leader>r
	imap <D-t> <Esc><D-t>
	imap <D-r> <Esc><D-r>

	" Navigate through buffers using Ctrl-Tab and Ctrl-Shift-Tab
	map <C-Tab> :bn<CR>
	map <C-S-Tab> :bp<CR>

	" Ctrl + Space for omnifunc automcomplete.
	imap <C-Space> <C-X><C-O>

	" Change buffers with Cmd-1, ..., Cmd-5.
	nmap <D-1> <Plug>BufTabLine.Go(1)
	nmap <D-2> <Plug>BufTabLine.Go(2)
	nmap <D-3> <Plug>BufTabLine.Go(3)
	nmap <D-4> <Plug>BufTabLine.Go(4)
	nmap <D-5> <Plug>BufTabLine.Go(5)

	" Appearance.
	colo dracula
	" set guifont=Operator\ Mono\ Book:h14 linespace=1
	set guifont=Monaco:h13 linespace=1
	" set guifont=MonoLisa:h11 linespace=1
	"colo base16-one-light
	"colo base16-onedark
	hi StatusLine   gui=bold guifg=#ffffff guibg=#000000
	hi StatusLineNC gui=bold guifg=#999999 guibg=#d0d0d0
endif


" ----------
" Deprecated
" ----------

" Ack.
" let g:ackprg = 'rg --vimgrep --ignore-vcs --no-heading --smart-case --iglob !node_modules/ --iglob !.git/ --iglob !.DS_Store --iglob !vendor/ --iglob !tmp/ --iglob !tags --sort-files'"
"nnoremap <Leader>a :Ack!<Space>''<Left>
"nnoremap <Leader>A :Ack! <cword><CR> " Searches the project for the word under the cursor.

" CtrlPFunky.
" let g:ctrlp_funky_matchtype = 'path'
" let g:ctrlp_funky_syntax_highlight = 1

" vim-session.
" let g:session_autoload = 'no'
" let g:session_autosave = 'yes'
" let g:session_autosave_silent = 1
" let g:session_directory = '~/.cache/vim-session/'

" ctrlsf.
" let g:ctrlsf_auto_close = 0
" let g:ctrlsf_position = 'bottom'
" let g:ctrlsf_winsize = '200'

" completor.vim.
" let g:completor_complete_options = 'menu,menuone,noinsert'
" let g:completor_completion_delay = 500
" let g:completor_blacklist = ['tagbar', 'netrw', 'gitcommit', 'gitrebase']
" let g:completor_php_omni_trigger = '([$\w]+|use\s*|->[$\w]*|::[$\w]*|implements\s*|extends\s*|class\s+[$\w]+|new\s*)$'
" let g:completor_python_binary = '/usr/local/bin/python3'

" nnoremap <D-r> :CtrlPFunky<CR>
" nnoremap <D-R> :execute 'CtrlPFunky ' . expand('<cword>')<CR>
