" vim:set ts=2 sts=2 sw=2 expandtab:

source ~/.vim/config/plugins.vim

set nocompatible
set autoread                  " Reload changed files.
set ffs=unix,dos,mac
set enc=utf-8
set fenc=utf-8
set modeline                  " Support modelines

set nobackup
set nowritebackup
set noswapfile
set history=1000
set hidden                    " Allow unsaved buffers.

set shortmess=aAI               " Use all the abbreviations, hide intro msg, etc.
set report=0
set nostartofline               " Don't move the cursor to the start of lines.

set wildmenu                    " Use wild menu for tab-completion.
set wildmode=longest:full

set backspace=indent,eol,start  " Backspace over everything.
set whichwrap+=<,>,[,]          " Cursor keys move to prev/next lines too.


set incsearch                   " Incremental search.
set hlsearch                    " Highlight search matches.
set nohlsearch                  " Do not highlight search matches.
set wrapscan                    " Wrap when searching.
set gdefault                    " Default to replacing all ocurrences when searching & replacing.

set ignorecase                  " ignore case when searching
set smartcase                   " don't ignore case when pattern is not lowercase

                                " show trailing whitespace
set list listchars=tab:»·,trail:·

set number                      " Show line numbers.
set showmatch                   " Show matching brackets.
set ruler                       " Show cursor position.

"set cursorline                  " Highlight the current line.

set title                       " Set filename as terminal title.
set titleold=
set laststatus=2                " Always show the status bar.
set scrolloff=3                 " Always show 3 lines of context around the cursor.
set nowrap                      " Do not wrap long lines.

colorscheme default
set textwidth=120                " Set text width at 120 chars.
set colorcolumn=80               " Show column width indicator.

set vb                           " Use visual bells instead of sound.
"set v_vb=                       " Turn off sound.

set autoindent                  " Automatic indentation.
set smartindent
"set cindent
set copyindent                  " Preserve identation whe copy/pasting.

set tabstop=4
set softtabstop=4
set expandtab                   " Expand tabs to spaces.
set shiftwidth=4                " Autoindent step.
set smarttab
set formatoptions+=n            " Recognize numbered lists.
set formatoptions-=t            " Do not break lines at textwidth col.

" Autocomplete.
set completeopt=menu,longest,menuone

syntax on                       " Enable syntax highlighting.
filetype plugin indent on       " Enable automatic loading of language-specific files.


source ~/.vim/config/filetypes.vim
source ~/.vim/config/mappings.vim
source ~/.vim/config/commands.vim



" Fixes some bug with ftplugin (see http://stackoverflow.com/questions/16902317/vim-slow-with-ruby-syntax-highlighting).
"let g:ruby_path="/usr/bin/ruby"
