tap 'shivammathur/php'

brew 'curl'
brew 'dateutils'
brew 'ffmpeg'
brew 'gh'
brew 'git'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'go'
brew 'gpg'
brew 'instaloader'
brew 'jq'
brew 'lazygit'
brew 'midnight-commander'
brew 'mas'
brew 'neovim'
brew 'posting'
brew 'python'
brew 'ripgrep'
brew 'ruby'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'subversion'
brew 'svn'
brew 'tldr'
brew 'wget'
brew 'yt-dlp'

cask '1password'
cask '1password-cli'
cask 'adobe-acrobat-reader'
cask 'arq'
cask 'chatgpt-classic'
cask 'claude'
cask 'claude-code@latest'
cask 'conductor'
cask 'crossover'
cask 'cyberduck'
cask 'dash'
cask 'devutils'
cask 'docker-desktop'
cask 'dotnet-sdk'
cask 'firefox'
cask 'font-courier-prime'
cask 'font-departure-mono'
cask 'font-ibm-plex-mono'
cask 'font-input'
cask 'font-jetbrains-mono'
cask 'font-roboto-mono'
cask 'font-sf-mono'
cask 'font-source-code-pro'
cask 'font-terminus'
cask 'ghostty'
cask 'godot-mono'
cask 'google-chrome'
cask 'httpie-desktop'
cask 'iina'
cask 'ioquake3'
cask 'licecap'
cask 'mactex'
cask 'macvim-app'
cask 'microsoft-teams'
cask 'netnewswire'
cask 'ngrok'
cask 'numi'
cask 'openemu'
cask 'playdate-simulator'
cask 'poedit'
cask 'querious'
cask 'rapidapi'
cask 'rar'
cask 'signal@beta'
cask 'slack'
cask 'steam'
#cask 'tableplus'
cask 'texmacs'
cask 'the-unarchiver'
cask 'tomatobar'
cask 'tower'
cask 'transmission'
cask 'unity'
cask 'unity-hub'
cask 'utm'
cask 'visual-studio-code'
cask 'whatsapp'
cask 'zed'
cask 'zoom'

brew 'mysql'
brew 'nginx'
brew 'nvm'
brew 'php'
brew 'php@7.4'
brew 'php@8.0'
brew 'phpmyadmin'
brew 'pnpm'

# Generate the following list with this command:
# mas list | sort -b -f -k2 | awk '{printf "mas "}{printf "\""}{for (i=2; i<NF; i++) printf $i " "}{printf "\""}{print ", id: " $1}' | sed 's/ ",/",/g'
mas "Amphetamine", id: 937984704
mas "Bear", id: 1091189122
mas "Broadcasts", id: 1469995354
mas "Day One", id: 1055511498
mas "Deliveries", id: 290986013
mas "Developer", id: 640199958
mas "HP", id: 1474276998
mas "Keynote", id: 361285480
mas "Kindle", id: 302584613
mas "Mela", id: 1568924476
mas "Numbers", id: 361304891
mas "Pages", id: 361309726
mas "Pixelmator Pro", id: 1289583905
mas "Sofa", id: 1276554886
mas "Streaks", id: 963034692
mas "TestFlight", id: 899247664
#mas "Tot", id: 1491071483
mas "Velja", id: 1607635845
mas "Wallaroo", id: 1630565980
mas "World Clock", id: 956377119
mas "Xcode", id: 497799835

# Safari extensions.
mas "1Password for Safari", id: 1569813296
#mas "Adblock Plus", id: 1432731683
mas "Keyword Search", id: 1558453954
#mas "Tampermonkey", id: 1482490089
mas "Wipr", id: 1662217862
