# ------
# Prompt
# ------
set_prompt() {
	if [[ "$TERM" = "dumb" ]]; then
		export PROMPT="%# "
	else
		#PROMPT='%n@%m:%15<..<%~%<<%# '
		local path="%F{248}%(4~|%-1~/…/%2~|%3~)%f"
		local symbol="%(!.%F{198}#%f.%F{148}>%f)"

		export PROMPT="$path%f $symbol "
	fi
}
set_prompt

# ------
# Basics
# ------
export EDITOR="$(which vim)"
export GREP_OPTIONS='--color=auto'
export LSCOLORS=Exfxcxdxbxegedabagacad

# --------
# Homebrew
# --------
if [[ -e "/usr/local/bin/brew" ]]; then eval $(/usr/local/bin/brew shellenv); fi # Homebrew (x86)
if [[ -e "/opt/homebrew/bin/brew" ]]; then eval $(/opt/homebrew/bin/brew shellenv); fi # Homebrew (Apple Silicon)

# ----
# PATH
# ----
if [[ -d "$HOME/.composer/vendor/bin" ]]; then export PATH="$HOME/.composer/vendor/bin:$PATH"; fi # Composer-installed binaries (Valet, etc.)
if [[ -n "$HOMEBREW_PREFIX" && -d "$HOMEBREW_PREFIX/opt/ruby/bin" ]]; then export PATH="$HOMEBREW_PREFIX/opt/ruby/bin:$PATH"; fi # Brew-installed Ruby.
if [[ -d "$HOME/.go/" ]]; then export GOPATH="$HOME/.go/"; export PATH="$HOME/.go/bin:$PATH"; fi # GOPATH
if [[ -d "$HOME/.bin" ]]; then export PATH="$HOME/.bin:$PATH"; fi # ~/.bin

# ------------------------------------------------------
# Temporarily switch between versions of PHP, Node, etc.
# ------------------------------------------------------
switch_version() {
	case "$1" in
		composer|phpunit)
			if [[ -z "$2" ]]; then
				ln -sf $(ls "$HOME/.bin/${1}"@* | sort -r | head -1) "$HOME/.bin/${1}"
			elif [[ -e "$HOME/.bin/${1}@${2}" ]]; then
				ln -sf "$HOME/.bin/${1}@${2}" "$HOME/.bin/${1}"
			fi

			;;
		php)
			# Remove current PATH override, if any.
			export PATH=$(echo $(sed -E "s|:?${HOMEBREW_PREFIX}/opt/${1}@[0-9.]+/bin:?||g" <<< $PATH))

			if [[ -n "$2" && -e "$HOMEBREW_PREFIX/opt/${1}@${2}" ]]; then
				export PATH="$HOMEBREW_PREFIX/opt/${1}@${2}/bin:$PATH"
			fi

			;;
	esac
}

# -------
# Aliases
# -------
alias ls="ls -G"
alias ll="ls -lG"
alias ~="cd ~"
alias ..="cd .."


# NVM.
export NVM_DIR="$HOME/.nvm"
[ -s "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" ] && \. "$HOMEBREW_PREFIX/opt/nvm/nvm.sh"
[ -s "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm" ] && \. "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm"

if [[ -e "$HOME/.zshrc.work" ]]; then source "$HOME/.zshrc.work"; fi
